version: "2"

services:
    db:
        image: mariadb
        container_name: riset-db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: your_mysql_root_password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        # volumes:
        #     - dbdata:/var/lib/mysql/
        #     - ./mysql/my.cnf:/etc/mysql/my.cnf
        # networks:
        #     - app-network
    app:
        image: docker.io/bitnami/laravel:9
        container_name: riset-app
        ports:
            - "8000:8000"
        environment:
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_USERNAME=bn_myapp
            - DB_DATABASE=bitnami_myapp
        volumes:
            - ".:/app"
        depends_on:
            - db
